# Generated by Django 5.1.1 on 2024-11-09 06:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('areas', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='puerta',
            name='area',
        ),
        migrations.CreateModel(
            name='PuertasAreas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='areas.area')),
                ('puerta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='areas.puerta')),
            ],
        ),
        migrations.AddField(
            model_name='puerta',
            name='areas',
            field=models.ManyToManyField(related_name='puertas', through='areas.PuertasAreas', to='areas.area'),
        ),
    ]
