# Generated by Django 5.1.1 on 2024-11-09 22:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('areas', '0002_remove_puerta_area_puertasareas_puerta_areas'),
    ]

    operations = [
        migrations.CreateModel(
            name='Zona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True)),
                ('activo', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='ZonasAreas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='areas.area')),
                ('zona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='areas.zona')),
            ],
        ),
        migrations.AddField(
            model_name='area',
            name='zonas',
            field=models.ManyToManyField(related_name='zonas', through='areas.ZonasAreas', to='areas.zona'),
        ),
    ]
