# Generated by Django 5.1.1 on 2024-11-29 04:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('areas', '0003_zona_zonasareas_area_zonas'),
        ('usuarios', '0007_alter_profilerole_fecha_vencimiento'),
    ]

    operations = [
        migrations.CreateModel(
            name='PuertasRoles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('puerta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='areas.puerta')),
                ('rol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.roles')),
            ],
        ),
    ]
