# Generated by Django 5.1.1 on 2024-11-01 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='roles',
            field=models.ManyToManyField(related_name='profiles', to='usuarios.roles'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='imagen_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
