# Generated by Django 5.1.1 on 2024-11-01 13:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_profile_roles_alter_profile_imagen_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='roles',
        ),
    ]
