# Generated by Django 5.1.1 on 2024-11-28 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0005_profilerole'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='sexo',
            field=models.CharField(blank=True, choices=[('M', 'Masculino'), ('F', 'Femenino'), ('O', 'Otro')], max_length=10, null=True),
        ),
    ]
