# Generated by Django 5.1.1 on 2024-11-28 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0006_alter_profile_sexo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profilerole',
            name='fecha_vencimiento',
            field=models.DateField(blank=True, null=True),
        ),
    ]
