# Generated by Django 5.1.1 on 2024-11-29 03:25

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('areas', '0003_zona_zonasareas_area_zonas'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Movimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=40)),
                ('hora', models.TimeField(default=datetime.datetime.now)),
                ('fecha', models.DateField(default=datetime.datetime.now)),
            ],
        ),
        migrations.CreateModel(
            name='MovimientoPuerta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movimiento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='atencion.movimiento')),
                ('puerta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='areas.puerta')),
            ],
        ),
        migrations.CreateModel(
            name='MovimientoUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movimiento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='atencion.movimiento')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
