# Generated by Django 5.1.1 on 2024-11-01 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atencion', '0002_alter_puertamovimiento_movimiento_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movimiento',
            name='hora',
            field=models.TimeField(default='18:51:54'),
        ),
    ]
