# Generated by Django 5.1.1 on 2024-11-09 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atencion', '0004_alter_movimiento_hora'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movimiento',
            name='hora',
            field=models.TimeField(default='16:15:12'),
        ),
    ]
