# Generated by Django 5.1.1 on 2024-11-25 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atencion', '0006_alter_movimiento_hora_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movimiento',
            name='hora',
            field=models.TimeField(default='21:39:30'),
        ),
    ]
